version: 0.2

phases:
  install:
    commands:
      - echo Installing .NET SDK
      - powershell -Command "Invoke-WebRequest -Uri https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.ps1 -OutFile dotnet-install.ps1"
      - powershell -Command ".\dotnet-install.ps1 -Version 8.0.100 -InstallDir 'C:\Program Files\dotnet'"
      - $env:PATH = "C:\Program Files\dotnet;" + $env:PATH
      - dotnet --version
  build:
    commands:
      - echo Build started on `date`
      - dotnet restore
      - dotnet build
  post_build:
    commands:
      - echo Build completed on `date`
      - dotnet publish -c Release -o publish
      - dir publish

artifacts:
  files:
    - publish/**/*