version: 0.2

phases:
  install:
    commands:
      - echo Installing .NET 8 SDK
      - wget https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh
      - chmod +x dotnet-install.sh
      -  ./dotnet-install.sh --version 8.0.303 --verbose
      - export PATH=$PATH:/usr/share/dotnet
      - dotnet --version
      - /root/.dotnet/dotnet --version
  build:
    commands:
      - echo Build started on `date`
      - dotnet restore
      - dotnet build
  post_build:
    commands:
      - echo Build completed on `date`
      - dotnet publish -c Release
      - aws cloudformation package --template-file cloudformationTemplate.yml --s3-bucket yevhen --output-template-file outputCloudFormationTemplate.yml
      - ls -la ./publish

artifacts:
  files:
    - Artifacts/AwsEc2Subtask4.zip
    - outputCloudFormationTemplate.yml

cache:
  paths:
    - '/root/.nuget/packages/**/*'